---
title: "primary"
author: "Shuai Yuan"
date: "11/18/2023"
output: html_document
---

## Intro

Trying to build a RNN model for bclass first

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(keras)
library(tensorflow)
```

```{r, include=FALSE, echo=FALSE}
library(keras)
library(tensorflow)
library(reticulate)
path_to_python <- "/Users/shuai/.pyenv/versions/3.9.18/bin/python3.9"
virtualenv_create("r-reticulate", python = path_to_python)
install_tensorflow(envname = "r-reticulate")
install_keras(envname = "r-reticulate")
```


```{r}
use_virtualenv("r-reticulate")
```

```{r}
set.seed(52032)
partitions <- claims_clean %>%
  initial_split(prop = 0.8)

train_text <- training(partitions) %>%
  pull(text_clean)
train_labels <- training(partitions) %>%
  pull(bclass) %>%
  as.numeric() - 1
```

```{r}
# create a preprocessing layer
preprocess_layer <- layer_text_vectorization(
  standardize = NULL,
  split = 'whitespace',
  ngrams = NULL,
  max_tokens = NULL,
  output_mode = 'tf_idf'
)

preprocess_layer %>% adapt(train_text)
```

```{r}
model <- keras_model_sequential() %>%
  preprocess_layer() %>%
  layer_embedding(input_dim = 38723,output_dim = 16)%>%
  layer_lstm(units = 16) %>%
  layer_dense(units = 1, activation = 'sigmoid')

summary(model)

model %>% compile(
  loss = 'binary_crossentropy',
  optimizer = 'adam',
  metrics = 'binary_accuracy'
)
```

```{r}
history <- model %>%
  fit(train_text, 
      train_labels,
      validation_split = 0.3,
      batch_size = 50,
      epochs = 5)
```

```{r}
save_model_tf(model, "results/lstm-model-2")
```

```{r}
load('data/claims-test.RData')
load('data/claims-raw.RData')
source('scripts/preprocessing.R')
tf_model <- load_model_tf('results/lstm-model-2')

# apply preprocessing pipeline
clean_df <- claims_test %>%
  slice(1:100) %>%
  parse_data() %>%
  select(.id, text_clean)

# grab input
x <- clean_df %>%
  pull(text_clean)

# compute predictions
preds <- predict(tf_model, x) %>%
  as.numeric()

class_labels <- claims_raw %>% pull(bclass) %>% levels()

pred_classes <- factor(preds > 0.5, labels = class_labels)

# export (KEEP THIS FORMAT IDENTICAL)
pred_df <- clean_df %>%
  bind_cols(bclass.pred = pred_classes) %>%
  select(.id, bclass.pred)

save(pred_df, file = 'results/lstm2-preds.RData')
```

